stages:
- build
- release

build:
  stage: build
  image: python:3.7
  only:
  - master
  script:
  - python setup.py bdist_wheel
  - pip3 install wheel
  artifacts:
    expire_in: 2 months
    paths:
    - dist/

release:
  stage: release
  image: python:3.7
  only:
  - master
  script:
  - pip3 install gitlab-release
  artifacts:
    paths:
    - dist/*whl
