stages:
- build
- release

variables:
  CFLAGS: -I/usr/include/hdf5/serial
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: python:3.7
  only:
  - tags
  script:
  - apt-get update -qq
      && apt-get install -y --no-install-recommends
      gfortran swig libatlas-base-dev liblapack-dev
      libhdf5-dev libfftw3-dev build-essential
  - pip3 install poetry wheel
  - pip3 install numpy cython
  - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/

release:tag:
  stage: release
  image: python:3.7
  only:
  - tags
  script:
  - pip3 install gitlab-release
  - pip3 install twine
  - echo -e '[pypi]' >> ~/.pypirc
  - echo -e 'repository = https://pkg.microquake.org' >> ~/.pypirc
  - echo -e 'username = micro' >> ~/.pypirc
  - echo -e 'password = quake' >> ~/.pypirc
  - twine upload --verbose dist/*whl
  - gitlab-release --link-artifact ./dist/*whl
  artifacts:
    paths:
    - dist/*whl
