[tool.poetry]
name = "xseis2"
version = "0.1.0"
description = ""
authors = ["Philip Dales"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
numpy = "^1.16"

[tool.poetry.dev-dependencies]
cython = "^0.29.7"
