* Questions
- outlier affecting linear fit
- how noisy individual ccf measurements compared to avg
-

* Data structures
- xcorrs for all pairs (in memory)
- 1 hour xcorrs (disk- grouped either by pair or by hour)
- ccf hourly vchange measurements (database on disk)
- station hourly vchange measurements (database on disk)

* Steps
- compute ccfs, unique channel pairs
- compare to ref
- avg ccf measurements to get station change, remove outlier ccfs
- update ref (qc)


Computing dvv between all ccfs and doing Bayesian inversion is the most robust, given the GF will change all the time. That is not very practical though because every time you run the inversion the entire time series will change. This is in an operational sense not great. Most practical is to compare current with immediately previous, since then you can calc dvv between any two times by just integrating changes in between. Unfortunately then you are very susceptible to propagating errors. I do the latter, but weighted sum to reduce influence of propagating errors. Static reference generally not a great idea, due to changing medium. Ditto stack of long time series

With regard to what you measure, tidal strain might be measurable, but will be small compared to induced changes. Diurnal temp not very relevant given insulation of rock above. You will see large seasonal dvv changes related to temp changes at OT givem the big change in temp from summer to winter. What you mostly measure though will be changes in fracture density though. Everywhere we monitor we see long term decrease in dvv. Hence it is very important to calibrate and remove damage model a la my Kilauea stuff. Stress changes quite small in comparison and takes quite a bit of work to extract

Dvv decrease on order or 1% per year typically from damage in mine

Estimate damage model from Cumulative apparent volume from seismicity


wg-quick up philipped
wg-quick down philipped
ssh jumphost
ssh 10.95.74.80
Password123$

* Questions
- [ ] Fix zero mid for second regression?
- [ ] Use all lag times or only after expected direct arrival?
- [ ] Always regress causal/acausal together?
- [ ] Determining best window size?

* Implentation
- From testing, measuring lag from cross-correlation much more robust than mwcs. Subsample resolution achieved by interpolating ifft


* Stress change (info from gerrits paper)

- coda will decay exponentially up to ~0.5 seconds lag time

- In this lag time travel time delays will range from 0 to 2.5e-4 seconds

- These changes are less than the sample spacing so phase shift measurements need to be made in frequency domain via linear regression of unwrapped cross-spectrum phase

- expect to make measurements in band 100-240 Hz

- Hope to measure changes on the order of 0.01% dv/v

- 10 second sections, whitened between 20-240 Hz and one-bit normalised

- Coda stable after 1 hour (i.e monitoring time resolution of 1 hour)

- To approximate the values of the velocity change between sensors we used a 3D triangulation-based linear interpolation method.
